#include "gtest/gtest.h"

#include "kompute/Kompute.hpp"

#ifdef KOMPUTE_VERSION_MAJOR
#define KOMPUTE_VERSION_MAJOR_DEFINED 1
#else
#define KOMPUTE_VERSION_MAJOR_DEFINED 0
#endif

#ifdef KOMPUTE_VERSION_MINOR
#define KOMPUTE_VERSION_MINOR_DEFINED 1
#else
#define KOMPUTE_VERSION_MINOR_DEFINED 0
#endif

#ifdef KOMPUTE_VERSION_PATCH
#define KOMPUTE_VERSION_PATCH_DEFINED 1
#else
#define KOMPUTE_VERSION_PATCH_DEFINED 0
#endif

#ifdef KOMPUTE_VERSION_STRING
#define KOMPUTE_VERSION_STRING_DEFINED 1
#else
#define KOMPUTE_VERSION_STRING_DEFINED 0
#endif

TEST(TestVersionDefined, MacrosDefined)
{
    EXPECT_EQ(KOMPUTE_VERSION_MAJOR_DEFINED, 1);
    EXPECT_EQ(KOMPUTE_VERSION_MINOR_DEFINED, 1);
    EXPECT_EQ(KOMPUTE_VERSION_PATCH_DEFINED, 1);
    EXPECT_EQ(KOMPUTE_VERSION_STRING_DEFINED, 1);
}
