var searchData=
[
  ['opalgobase',['OpAlgoBase',['../classkp_1_1OpAlgoBase.html',1,'kp::OpAlgoBase'],['../classkp_1_1OpAlgoBase.html#a8315949fc5a931b787ccbfe32f5bb118',1,'kp::OpAlgoBase::OpAlgoBase()'],['../classkp_1_1OpAlgoBase.html#accf997b6e3343080d51916b0a8c252dd',1,'kp::OpAlgoBase::OpAlgoBase(std::shared_ptr&lt; vk::PhysicalDevice &gt; physicalDevice, std::shared_ptr&lt; vk::Device &gt; device, std::shared_ptr&lt; vk::CommandBuffer &gt; commandBuffer, std::vector&lt; std::shared_ptr&lt; Tensor &gt;&gt; &amp;tensors, const Workgroup &amp;komputeWorkgroup={}, const Constants &amp;specializationConstants={})'],['../classkp_1_1OpAlgoBase.html#a48db9aef4edb1853dfff28bc0f8387d7',1,'kp::OpAlgoBase::OpAlgoBase(std::shared_ptr&lt; vk::PhysicalDevice &gt; physicalDevice, std::shared_ptr&lt; vk::Device &gt; device, std::shared_ptr&lt; vk::CommandBuffer &gt; commandBuffer, std::vector&lt; std::shared_ptr&lt; Tensor &gt;&gt; &amp;tensors, std::string shaderFilePath, const Workgroup &amp;komputeWorkgroup={}, const Constants &amp;specializationConstants={})'],['../classkp_1_1OpAlgoBase.html#a662ecc57c6d050da009042247f9d88af',1,'kp::OpAlgoBase::OpAlgoBase(std::shared_ptr&lt; vk::PhysicalDevice &gt; physicalDevice, std::shared_ptr&lt; vk::Device &gt; device, std::shared_ptr&lt; vk::CommandBuffer &gt; commandBuffer, std::vector&lt; std::shared_ptr&lt; Tensor &gt;&gt; &amp;tensors, const std::vector&lt; uint32_t &gt; &amp;shaderDataRaw, const Workgroup &amp;komputeWorkgroup={}, const Constants &amp;specializationConstants={})']]],
  ['opalgolhsrhsout',['OpAlgoLhsRhsOut',['../classkp_1_1OpAlgoLhsRhsOut.html',1,'kp::OpAlgoLhsRhsOut'],['../classkp_1_1OpAlgoLhsRhsOut.html#a4854d30a02eed2ed9a8322f029745108',1,'kp::OpAlgoLhsRhsOut::OpAlgoLhsRhsOut()'],['../classkp_1_1OpAlgoLhsRhsOut.html#a9e3d3797b9565dd96bde6929f22aa116',1,'kp::OpAlgoLhsRhsOut::OpAlgoLhsRhsOut(std::shared_ptr&lt; vk::PhysicalDevice &gt; physicalDevice, std::shared_ptr&lt; vk::Device &gt; device, std::shared_ptr&lt; vk::CommandBuffer &gt; commandBuffer, std::vector&lt; std::shared_ptr&lt; Tensor &gt;&gt; tensors, const Workgroup &amp;komputeWorkgroup={})']]],
  ['opbase',['OpBase',['../classkp_1_1OpBase.html',1,'kp::OpBase'],['../classkp_1_1OpBase.html#ad0b568269057a48cf5c71c5616bba750',1,'kp::OpBase::OpBase()'],['../classkp_1_1OpBase.html#af5f3f217e5e7263277bb5e900dafa279',1,'kp::OpBase::OpBase(std::shared_ptr&lt; vk::PhysicalDevice &gt; physicalDevice, std::shared_ptr&lt; vk::Device &gt; device, std::shared_ptr&lt; vk::CommandBuffer &gt; commandBuffer, std::vector&lt; std::shared_ptr&lt; Tensor &gt;&gt; &amp;tensors)']]],
  ['operator_5b_5d',['operator[]',['../classkp_1_1Tensor.html#a64ff1ca98d5380cc3916e13b20f7a509',1,'kp::Tensor']]],
  ['opmult',['OpMult',['../classkp_1_1OpMult.html',1,'kp::OpMult'],['../classkp_1_1OpMult.html#a295ede6f7f1b0b8add558a2dc3e3b838',1,'kp::OpMult::OpMult()'],['../classkp_1_1OpMult.html#af701bd5d001502f4b6af1bfa7000b8c2',1,'kp::OpMult::OpMult(std::shared_ptr&lt; vk::PhysicalDevice &gt; physicalDevice, std::shared_ptr&lt; vk::Device &gt; device, std::shared_ptr&lt; vk::CommandBuffer &gt; commandBuffer, std::vector&lt; std::shared_ptr&lt; Tensor &gt;&gt; tensors, const Workgroup &amp;komputeWorkgroup={})']]],
  ['optensorcopy',['OpTensorCopy',['../classkp_1_1OpTensorCopy.html',1,'kp::OpTensorCopy'],['../classkp_1_1OpTensorCopy.html#a412de294c41e5f73d6feb5fc7880182b',1,'kp::OpTensorCopy::OpTensorCopy()']]],
  ['optensorsyncdevice',['OpTensorSyncDevice',['../classkp_1_1OpTensorSyncDevice.html',1,'kp::OpTensorSyncDevice'],['../classkp_1_1OpTensorSyncDevice.html#aedd10f74c3d10b5e182501c9b4c24516',1,'kp::OpTensorSyncDevice::OpTensorSyncDevice()']]],
  ['optensorsynclocal',['OpTensorSyncLocal',['../classkp_1_1OpTensorSyncLocal.html',1,'kp::OpTensorSyncLocal'],['../classkp_1_1OpTensorSyncLocal.html#a843ba988f4229454cfe37970120ffbb6',1,'kp::OpTensorSyncLocal::OpTensorSyncLocal()']]]
];
