#include "kompute/shaders/shaderopmult.hpp"
#include "kompute/Manager.hpp"
#include "kompute/OpBase.hpp"
#include "kompute/OpMult.hpp"
#include "kompute/OpCreateTensor.hpp"
#include "kompute/OpMult.hpp"
#include "kompute/Tensor.hpp"
