name: C++ Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpp-tests:

    runs-on: ubuntu-18.04
    container: axsauze/kompute-builder:0.2

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: configure-cpp
      run: |
        cmake -Bbuild/ \
                  -DCMAKE_BUILD_TYPE=Debug                   \
                  -DKOMPUTE_OPT_INSTALL=0                    \
                  -DKOMPUTE_OPT_REPO_SUBMODULE_BUILD=1       \
                  -DKOMPUTE_OPT_BUILD_TESTS=1                \
                  -DKOMPUTE_OPT_ENABLE_SPDLOG=1
    - name: build-cpp
      run: |
        make mk_build_tests
    - name: test-cpp
      run: |
        export VK_ICD_FILENAMES=/swiftshader/vk_swiftshader_icd.json
        make mk_run_tests

